In [1]:
import pandas as pd
l=[]
for i in range(1,1001):
  if(i%2==0):
    l.append(i)
ds = pd.Series(l) 
print(ds)

0         2
1         4
2         6
3         8
4        10
       ... 
495     992
496     994
497     996
498     998
499    1000
Length: 500, dtype: int64


In [2]:
import pandas as pd
l=[]
for i in range(1000,2001):
    l.append(i)
ds = pd.Series(l)
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series and type
0       1000
1       1001
2       1002
3       1003
4       1004
        ... 
996     1996
997     1997
998     1998
999     1999
1000    2000
Length: 1001, dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1

In [3]:
import pandas as pd
l=[]
m=[]
for i in range(1,101):
  if(i%2==0):
    l.append(i)
  else:
    m.append(i)
ds1 = pd.Series(l)
ds2 = pd.Series(m)
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0       3
1       7
2      11
3      15
4      19
5      23
6      27
7      31
8      35
9      39
10     43
11     47
12     51
13     55
14     59
15     63
16     67
17     71
18     75
19     79
20     83
21     87
22     91
23     95
24     99
25    103
26    107
27    111
28    115
29    119
30    123
31    127
32    131
33    135
34    139
35    143
36    147
37    151
38    155
39    159
40    163
41    167
42    171
43    175
44    179
45    183
46    187
47    191
48    195
49    199
dtype: int64
Subtract two Series:
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
31    1
32    1
33    1
34    1
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    1
46    1
47    1
48    1
49    1
dtype: int64
Multiply two Series:
0        2
1    

In [4]:
import pandas as pd
l=[]
m=[]
for i in range(1,101):
  if(i%7==0):
    l.append(i)
  if(i%11==0):
    m.append(i)
le=len(l)-len(m)
for i in range(le):
  m.append(0)
ds1 = pd.Series(l)
ds2 = pd.Series(m)
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0      7
1     14
2     21
3     28
4     35
5     42
6     49
7     56
8     63
9     70
10    77
11    84
12    91
13    98
dtype: int64
Series2:
0     11
1     22
2     33
3     44
4     55
5     66
6     77
7     88
8     99
9      0
10     0
11     0
12     0
13     0
dtype: int64
Compare the elements of the said Series:
Equals:
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
dtype: bool
Greater than:
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12     True
13     True
dtype: bool
Less than:
0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10    False
11    False
12    False
13    False
dtype: bool


In [5]:


import numpy as np
import pandas as pd
l=[]
for i in range(10,1001,10):
    l.append(i)
np_array = np.array(l)
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)



NumPy array:
[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]
Converted Pandas series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


In [6]:
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [7]:
import pandas as pd
s = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
0          100
1          200
2          300
6       300.12
3          400
7          400
4          500
9        great
8           is
10    language
5       python
dtype: object


In [8]:


import pandas as pd
l=[]
for i in range(10,1001,10):
    l.append(i)
s = pd.Series(l)
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
new_s = s[s%7==0]
print(new_s)
new = s[s%5==0]
print(new)



Original Data Series:
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64

Subset of the above Data Series:
6      70
13    140
20    210
27    280
34    350
41    420
48    490
55    560
62    630
69    700
76    770
83    840
90    910
97    980
dtype: int64
0       10
1       20
2       30
3       40
4       50
      ... 
95     960
96     970
97     980
98     990
99    1000
Length: 100, dtype: int64


In [9]:
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.
import pandas as pd
l=[]
f=0
for j in range(2,1001):
  f=0
  for i in range(2,j):
    if (j % i) == 0:
      f=1
      break
  if(f==0):
      l.append(j)
print(l)
s = pd.Series(l)
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())
print(s.max())
print(s.min())

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
Original Data Series:
0        2
1        3
2        5
3        7
4       11
      ... 
163    971
164    977
165    983
166    991
167    997
Length: 168, dtype: int64
Mean of the said Da

In [10]:


import pandas as pd
x=[]
y=[]
z=[]
for i in range(1,1001):
  if(i%2==0):
    if(i%5!=0):
      y.append(i)
  else:
    if(i%7!=0):
      x.append(i)
    if(i%3!=0):
      z.append(i)
le=len(x)-len(y)
lf=len(x)-len(z)
for i in range(le):
  y.append(0)
for i in range(lf):
  z.append(0)
df = pd.DataFrame({'X':x, 'Y':y,'Z':z});
print(df)



       X   Y   Z
0      1   2   1
1      3   4   5
2      5   6   7
3      9   8  11
4     11  12  13
..   ...  ..  ..
424  991   0   0
425  993   0   0
426  995   0   0
427  997   0   0
428  999   0   0

[429 rows x 3 columns]


In [11]:
import pandas as pd
x=[]
y=[]
z=[]
for i in range(1,1001):
  if(i%2==0):
    if(i%5!=0):
      y.append(i)
  else:
    if(i%7!=0):
      x.append(i)
    if(i%3!=0):
      z.append(i)
le=len(x)-len(y)
lf=len(x)-len(z)
for i in range(le):
  y.append(0)
for i in range(lf):
  z.append(0)
df = pd.DataFrame({'X':x, 'Y':y,'Z':z});
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)

First 10 rows of the DataFrame:
    X   Y   Z
0   1   2   1
1   3   4   5
2   5   6   7
3   9   8  11
4  11  12  13
5  13  14  17
6  15  16  19
7  17  18  23
8  19  22  25
9  23  24  29


In [ ]:


import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv']))
s1 = df.iloc[6][0]
s2 = df.iloc[6][1]
s3 = df.iloc[6][2]
print("Details of the third moviee:")
print(third_movie)



In [ ]:


import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv']))
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values('title_year')
print("DataFrame based on title year.")
print(result)



In [ ]:
import pandas as pd
import io
from google.colab import files
uploaded=files.upload()
df = pd.read_csv(io.BytesIO(uploaded['movie_metadata.csv']))
small_df = df[['num_user_for_reviews','language','country','content_rating','budget','title_year']]
result = small_df.sort_values(by=['country', 'language'])
print("DataFrame based on title year.")
print(result)

In [15]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.69191517 0.68501356 0.13923663 0.48904327]
 [0.87569417 0.43956108 0.18138385 0.52056381]
 [0.45961911 0.262873   0.24885766 0.70471183]
 [0.237365   0.06222816 0.48233068 0.40765807]]
Minimum and Maximum Values:
0.06222815794408709 0.8756941663659276


In [16]:


import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)



Original Array:
[[6.18964840e-01 3.21425751e-01 9.11062434e-01 8.65865564e-01
  4.15274905e-01 6.27306334e-01 7.92388654e-01 6.80169232e-01
  6.70191717e-01 1.94727014e-01]
 [9.25125385e-04 2.08357253e-01 9.31102882e-02 2.06529053e-01
  3.09844692e-01 4.22544039e-01 5.52039674e-01 8.41766548e-03
  5.35787587e-01 8.20492632e-01]
 [4.75822108e-01 2.65449477e-01 7.23291999e-01 4.29891970e-01
  3.93968527e-01 2.10263333e-01 7.82649536e-02 9.69858973e-01
  4.02400410e-01 1.03146139e-01]
 [2.95208399e-01 4.30186315e-01 5.17383001e-01 6.60083759e-01
  3.25620698e-01 7.83377688e-01 1.01467135e-01 1.77279725e-01
  5.05234049e-02 3.71600719e-01]
 [1.61569330e-01 2.72010819e-01 9.25639796e-01 2.17354538e-01
  7.84782893e-01 3.09914524e-01 4.77735683e-01 8.13306689e-01
  8.06081942e-01 1.39211815e-01]
 [5.29808792e-01 4.74979067e-01 7.21426149e-01 6.79787070e-03
  3.54911814e-01 1.94726852e-01 8.48837569e-02 3.04959162e-01
  2.18077677e-01 8.64086653e-01]
 [9.94559835e-01 9.98793337e-01 5.73820319

In [17]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[102 161 141 105 263 186 173 175]


In [18]:
import numpy as np
x=np.arange(20)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[ 2 13  3 18  4  0 11  7 12 19 15  5  6  8 17 16 14  9  1 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
